apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.name }}-clusterip
spec:
  ports:
    - name: http
      port: {{ .Values.auth.servicePort }}
      targetPort: {{ .Values.auth.containerPort }}
  selector:
    app: {{ .Values.auth.components }}
